version: '3.8'

services:
   postgres-db:
      image: postgres:15.3
      container_name: blaze-db
      restart: always
      ports:
         - 5432:5432
      volumes:
         - ./postgres:/var/lib/postgresql/data
      environment:
         POSTGRES_DB: ${POSTGRES_DB}
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
